image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1870.83826,    0.     ,  654.97005 ,
            0.     , 1869.7689,  528.98147,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.15885, 0.205852, 0.0, 0.0, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1870.83826,    0.     ,  654.97005,    0.     ,
            0.     , 1869.7689,  528.98147,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]